#!/usr/bin/env python
import logging
import argh
from argh import arg
from retrycli import shell_command
import argparse

LOG = logging.getLogger(__name__)
LOG.setLevel(logging.DEBUG)

@argh.arg('shell_argument', nargs=argparse.REMAINDER, type=str, help='Shell command you want to retry')
def this(**kwargs):
    LOG.debug("Command: {0}".format(kwargs['shell_argument']))
    stdout = shell_command(**kwargs)
    print(stdout)


PARSER = argh.ArghParser()
PARSER.add_commands([this])
if __name__ == '__main__':
    FORMAT = '%(asctime)-15s %(name)s [%(levelname)s] : %(message)s'
    logging.basicConfig(format=FORMAT, level=logging.ERROR)
    PARSER.dispatch()
