#!/usr/bin/env python
import logging
import argh
from argh import arg
from retrycli import shell_command
import argparse

LOG = logging.getLogger(__name__)
LOG.setLevel(logging.ERROR)

@argh.arg('shell_argument', nargs=argparse.REMAINDER, type=str, help='Shell command you want to retry')
def this(**kwargs):
    LOG.debug("Command: {0}".format(kwargs['shell_argument']))
    shell_command(**kwargs)

if __name__ == '__main__':
    FORMAT = '%(asctime)-15s %(name)s [%(levelname)s] : %(message)s'
    logging.basicConfig(format=FORMAT, level=logging.ERROR)
    argh.dispatch_command(this)
